#!/usr/bin/env python3
"""
Brief Generator: Morning (7 AM)
Formats market intel + Wiggleez metrics into WhatsApp-friendly brief.
"""
import json
from datetime import datetime
import glob

def generate_morning_brief():
    """Compile morning brief from market intel + sales metrics."""
    
    # Read latest data files
    market_intel = {}
    sales_metrics = {}
    campaign_status = {}
    
    try:
        with open("data/wiggleez_metrics_today.json") as f:
            sales_metrics = json.load(f)
    except:
        sales_metrics = {"orders": 0, "revenue_qar": 0, "traffic_visitors": 0}
    
    try:
        with open("data/market_intel_today.json") as f:
            market_intel = json.load(f)
    except:
        market_intel = {}
    
    # Format brief for WhatsApp (emoji + concise)
    brief_text = f"""📊 MORNING BRIEF — {datetime.now().strftime('%Y-%m-%d')}

🏪 Wiggleez Performance
• Orders: {sales_metrics.get('orders', 0)}
• Revenue: {sales_metrics.get('revenue_qar', 0):,} QAR
• Traffic: {sales_metrics.get('traffic_visitors', 0)} visitors
• Conversion: {sales_metrics.get('conversion_rate', 0):.1f}%

📈 Markets
• Qatar DSX: {market_intel.get('qatar_dsx', {}).get('trend', 'stable')} ({market_intel.get('qatar_dsx', {}).get('change', 0):+.1f}%)
• S&P 500: {market_intel.get('sp500', {}).get('trend', 'stable')} ({market_intel.get('sp500', {}).get('change', 0):+.1f}%)
• Bitcoin: {market_intel.get('bitcoin', {}).get('trend', 'volatile')} ({market_intel.get('bitcoin', {}).get('change', 0):+.1f}%)

💼 Campaigns
• Emails sent: [pending]
• Responses: [pending]
• Calls scheduled: [pending]

⚠️ System
• J (Mac mini): ✓ Online
• H (VPS): ✓ Online
• Sync: ✓ Working

🎯 Today's Actions
1. Monitor email responses
2. Send WhatsApp follow-ups
3. Check market opportunities

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by J (Mac mini Pro)
{datetime.now().isoformat()}
"""
    
    # Also save structured JSON
    brief_json = {
        "timestamp": datetime.now().isoformat(),
        "brief_text": brief_text,
        "sales": sales_metrics,
        "markets": market_intel,
        "ready_to_send": True
    }
    
    return brief_json, brief_text

if __name__ == "__main__":
    brief_json, brief_text = generate_morning_brief()
    
    # Save JSON version
    with open("data/morning_brief.json", "w") as f:
        json.dump(brief_json, f, indent=2)
    
    # Save TXT version for WhatsApp
    with open("data/morning_brief.txt", "w") as f:
        f.write(brief_text)
    
    print(f"✓ Morning brief generated")
    print(f"\n{brief_text}")
